'use client';

import { useState } from 'react';
import { phoneInternational, stages, validateVacancy, visibleQuestions, type PreviewApplication, type Question, type QuestionKind, type Stage, type Vacancy } from '../../lib/careers-preview';
import { Alert, CountrySelect, Field, FileLink, countryName, sizeLabel } from './careers-ui';
import s from './careers.module.css';

type Props = { vacancies: Vacancy[]; applications: PreviewApplication[]; onVacancies: (items: Vacancy[]) => void; onApplications: (items: PreviewApplication[]) => void; initialApplication?: string; onTryApplication: () => void };
export function RecruitmentPreview({ vacancies, applications, onVacancies, onApplications, initialApplication, onTryApplication }: Props) {
  const [tab, setTab] = useState<'applications' | 'vacancies' | 'settings'>('applications');
  const [selectedId, setSelectedId] = useState(initialApplication || '');
  const [search, setSearch] = useState('');
  const [jobFilter, setJobFilter] = useState('');
  const [stageFilter, setStageFilter] = useState('');
  const [minExperience, setMinExperience] = useState('');
  const [country, setCountry] = useState('');
  const [showPhotos, setShowPhotos] = useState(true);
  const [editing, setEditing] = useState<Vacancy | null>(null);
  const [issue, setIssue] = useState('');
  const [note, setNote] = useState('');
  const [sender, setSender] = useState('');
  const [replyTo, setReplyTo] = useState('');
  const current = applications.find(application => application.id === selectedId);
  const results = applications.filter(application => {
    const searchable = [application.draft.givenName, application.draft.familyName, application.vacancy.title, ...Object.values(application.draft.answers).flat()].join(' ').toLowerCase();
    return (!search || searchable.includes(search.toLowerCase())) && (!jobFilter || application.vacancy.id === jobFilter) && (!stageFilter || application.stage === stageFilter) && (!country || application.draft.residence === country) && (!minExperience || Number(application.draft.relevantExperience) >= Number(minExperience));
  });
  function updateApplication(application: PreviewApplication) { onApplications(applications.map(item => item.id === application.id ? application : item)); }
  function selectTab(next: typeof tab) { setTab(next); setSelectedId(''); setEditing(null); setIssue(''); }
  function saveVacancy() {
    if (!editing) return;
    const cleaned = { ...editing, title: editing.title.trim(), questions: editing.questions.map(q => ({ ...q, label: q.label.trim(), options: q.options?.map(option => option.trim()).filter(Boolean) })) };
    const error = validateVacancy(cleaned);
    if (error) { setIssue(error); return; }
    const previous = vacancies.find(item => item.id === cleaned.id);
    const next = { ...cleaned, version: previous ? previous.version + 1 : 1 };
    onVacancies(previous ? vacancies.map(item => item.id === next.id ? next : item) : [...vacancies, next]);
    setEditing(null); setIssue('');
  }
  function patchQuestion(index: number, patch: Partial<Question>) { if (editing) setEditing({ ...editing, questions: editing.questions.map((q, at) => at === index ? { ...q, ...patch } : q) }); }
  function moveQuestion(index: number, offset: number) { if (!editing) return; const questions = [...editing.questions]; const next = index + offset; if (next < 0 || next >= questions.length) return; [questions[index], questions[next]] = [questions[next], questions[index]]; setEditing({ ...editing, questions }); }
  const stamp = (at: string) => new Date(at).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' });
  return <section className={s.adminArea}>
    <div className={s.sectionHeading}><div><span className={s.eyebrow}>ERP NEXT · PRODUCT PREVIEW</span><h1>Recruitment</h1><p>Review the workflow without changing real records.</p></div><button type="button" className={s.secondary} onClick={onTryApplication}>Try candidate flow ↗</button></div>
    <nav className={s.adminTabs} aria-label="Recruitment sections"><button type="button" className={tab === 'applications' ? s.tabActive : s.tab} onClick={() => selectTab('applications')}>Applicants <span>{applications.length}</span></button><button type="button" className={tab === 'vacancies' ? s.tabActive : s.tab} onClick={() => selectTab('vacancies')}>Vacancies <span>{vacancies.length}</span></button><button type="button" className={tab === 'settings' ? s.tabActive : s.tab} onClick={() => selectTab('settings')}>Email preview</button></nav>
    {issue && <Alert>{issue}</Alert>}
    {tab === 'applications' && !current && <>
      <div className={s.filters}><Field id="app-search" label="Search applicants"><input id="app-search" type="search" value={search} placeholder="Name, role or skills" onChange={event => setSearch(event.target.value)} /></Field><Field id="job-filter" label="Role"><select id="job-filter" value={jobFilter} onChange={event => setJobFilter(event.target.value)}><option value="">All roles</option>{vacancies.map(job => <option key={job.id} value={job.id}>{job.title}</option>)}</select></Field><Field id="stage-filter" label="Stage"><select id="stage-filter" value={stageFilter} onChange={event => setStageFilter(event.target.value)}><option value="">All stages</option>{stages.map(stage => <option key={stage}>{stage}</option>)}</select></Field></div>
      <details className={s.filterDetails}><summary>More filters</summary><div className={s.twoColumns}><Field id="experience-filter" label="Minimum relevant experience (years)"><input id="experience-filter" type="number" min="0" max="70" value={minExperience} onChange={event => setMinExperience(event.target.value)} /></Field><Field id="country-filter" label="Country of residence"><CountrySelect id="country-filter" value={country} onChange={setCountry} /></Field></div><button type="button" className={s.textButton} onClick={() => { setSearch(''); setJobFilter(''); setStageFilter(''); setMinExperience(''); setCountry(''); }}>Clear filters</button></details>
      <div className={s.sectionHeading}><p>{results.length} matching preview {results.length === 1 ? 'application' : 'applications'}</p><label className={s.checkbox}><input type="checkbox" checked={showPhotos} onChange={event => setShowPhotos(event.target.checked)} />Show profile photos</label></div>
      {!results.length && <div className={s.empty}><h2>{applications.length ? 'No matching applicants' : 'Your first applicant will appear here'}</h2><p>{applications.length ? 'Adjust the filters to see more profiles.' : 'Complete a preview application with test information, a photo and a CV. Then return here to review it.'}</p>{!applications.length && <button type="button" className={s.primary} onClick={onTryApplication}>Try the application form →</button>}</div>}
      <div className={s.applicantList}>{results.map(application => <button type="button" key={application.id} className={s.applicantCard} onClick={() => { setSelectedId(application.id); setNote(''); }}>{showPhotos && application.draft.photo ? <img className={s.avatar} src={application.draft.photo.dataUrl} alt="Candidate profile photo" /> : <span className={s.initialAvatar}>{application.draft.givenName.charAt(0)}{application.draft.familyName.charAt(0)}</span>}<span className={s.applicantCopy}><strong>{application.draft.givenName} {application.draft.familyName}</strong><span>{application.vacancy.title}</span><small>{countryName(application.draft.residence)} · {application.draft.relevantExperience} years relevant experience</small></span><span className={s.badge}>{application.stage}</span><span aria-hidden="true">→</span></button>)}</div>
    </>}
    {tab === 'applications' && current && <>
      <button type="button" className={s.textButton} onClick={() => setSelectedId('')}>← All applicants</button>
      <div className={s.profileTop}><div className={s.profileHeading}>{showPhotos && current.draft.photo && <img className={s.photoPreview} src={current.draft.photo.dataUrl} alt="Candidate profile photo" />}<div><h2>{current.draft.givenName} {current.draft.familyName}</h2><p>{current.vacancy.title}</p><small>{current.id} · Form version {current.vacancy.version}</small></div></div><Field id="profile-stage" label="Recruitment stage"><select id="profile-stage" value={current.stage} onChange={event => { const next = event.target.value as Stage; updateApplication({ ...current, stage: next, timeline: [...current.timeline, { text: `Stage changed to ${next} (preview only)`, at: new Date().toISOString() }] }); }}>{stages.map(stage => <option key={stage}>{stage}</option>)}</select></Field></div>
      <div className={s.detailGrid}>
        <section className={s.reviewCard}><h2>Contact information</h2><dl className={s.answers}><div><dt>Email</dt><dd>{current.draft.email}</dd></div><div><dt>Phone</dt><dd>{phoneInternational(current.draft)}{current.draft.whatsapp ? ' · WhatsApp' : ''}</dd></div><div><dt>Residence</dt><dd>{current.draft.city}, {countryName(current.draft.residence)}</dd></div><div><dt>Applying from</dt><dd>{countryName(current.draft.applyingFrom)}</dd></div><div><dt>Nationality · administrative information</dt><dd>{countryName(current.draft.nationality)}</dd></div></dl></section>
        <section className={s.reviewCard}><h2>Professional profile</h2><p>{current.draft.totalExperience} years total · {current.draft.relevantExperience} years relevant</p><p>{current.draft.languages.join(', ')}</p><p>Availability: {current.draft.availability}</p><span className={s.badge}>Self-declared · Not yet verified</span><p className={s.helper}>No automated ranking or photo-based evaluation.</p></section>
        <section className={s.reviewCard}><h2>Role questions</h2><dl className={s.answers}>{visibleQuestions(current.vacancy, current.draft).map(q => <div key={q.id}><dt>{q.label}</dt><dd>{Array.isArray(current.draft.answers[q.id]) ? (current.draft.answers[q.id] as string[]).join(', ') : current.draft.answers[q.id] || 'Not provided'}</dd></div>)}</dl></section>
        <section className={s.reviewCard}><h2>Documents</h2><p className={s.helper}>Browser-session copies only. Not uploaded or scanned.</p>{[...(current.draft.cv ? [current.draft.cv] : []), ...current.draft.documents].map((file, index) => <div className={s.fileRow} key={`${file.name}-${index}`}><span><strong>{file.name}</strong><small>{sizeLabel(file.size)}</small></span><FileLink file={file} /></div>)}<p>Future openings: {current.draft.futureTalent ? 'Opted in (simulated)' : 'Not opted in'}</p></section>
        <section className={s.reviewCard}><h2>Recruiter notes</h2><p className={s.helper}>Internal workspace preview. Notes are not part of the candidate form.</p>{current.notes.map((item, index) => <div key={index} className={s.note}><small>{stamp(item.at)}</small><p>{item.text}</p></div>)}<Field id="recruiter-note" label="Add a note"><textarea id="recruiter-note" rows={3} value={note} maxLength={2000} onChange={event => setNote(event.target.value)} /></Field><button type="button" className={s.secondary} disabled={!note.trim()} onClick={() => { updateApplication({ ...current, notes: [...current.notes, { text: note.trim(), at: new Date().toISOString() }] }); setNote(''); }}>Save preview note</button></section>
        <section className={s.reviewCard}><h2>Activity</h2><ol className={s.timeline}>{current.timeline.map((event, index) => <li key={index}><strong>{event.text}</strong><small>{stamp(event.at)}</small></li>)}</ol><p className={s.helper}>Changing a stage does not send emails, create employees or reserve service appointments.</p></section>
      </div>
    </>}
    {tab === 'vacancies' && !editing && <>
      <div className={s.sectionHeading}><p>Example vacancies · Changes affect this session only.</p><button type="button" className={s.primary} onClick={() => { setIssue(''); setEditing({ id: `preview-job-${Date.now()}`, title: '', department: 'Technical', location: 'Aruba', contract: 'Full-time', summary: '', responsibilities: [''], requirements: [''], status: 'Draft', cvRequired: true, version: 1, questions: [{ id: 'experience-summary', label: 'Tell us about your relevant experience.', kind: 'textarea', required: true }] }); }}>＋ New vacancy</button></div>
      <div className={s.vacancyGrid}>{vacancies.map(job => <article className={s.jobCard} key={job.id}><div className={s.sectionHeading}><span className={s.eyebrow}>{job.department}</span><span className={s.badge}>{job.status}</span></div><h2>{job.title}</h2><p>{job.questions.length} role questions · Version {job.version}</p><p>{applications.filter(application => application.vacancy.id === job.id).length} preview applications</p><button type="button" className={s.secondary} onClick={() => { setIssue(''); setEditing(JSON.parse(JSON.stringify(job)) as Vacancy); }}>Edit vacancy & questions →</button></article>)}</div>
    </>}
    {tab === 'vacancies' && editing && <section className={s.editor}>
      <button type="button" className={s.textButton} onClick={() => { setEditing(null); setIssue(''); }}>← Back to vacancies</button><h2>{vacancies.some(job => job.id === editing.id) ? 'Edit vacancy' : 'Create vacancy'}</h2>
      <div className={s.twoColumns}><Field id="job-title" label="Job title"><input id="job-title" value={editing.title} maxLength={100} onChange={event => setEditing({ ...editing, title: event.target.value })} /></Field><Field id="job-department" label="Department"><input id="job-department" value={editing.department} maxLength={80} onChange={event => setEditing({ ...editing, department: event.target.value })} /></Field></div>
      <div className={s.twoColumns}><Field id="job-location" label="Location"><input id="job-location" value={editing.location} maxLength={100} onChange={event => setEditing({ ...editing, location: event.target.value })} /></Field><Field id="job-status" label="Publication status"><select id="job-status" value={editing.status} onChange={event => setEditing({ ...editing, status: event.target.value as Vacancy['status'] })}>{['Draft', 'Open', 'Paused', 'Closed'].map(status => <option key={status}>{status}</option>)}</select></Field></div>
      <Field id="job-summary" label="About the role"><textarea id="job-summary" value={editing.summary} rows={3} maxLength={1200} onChange={event => setEditing({ ...editing, summary: event.target.value })} /></Field>
      <Field id="job-responsibilities" label="Responsibilities · one per line"><textarea id="job-responsibilities" value={editing.responsibilities.join('\n')} rows={3} maxLength={2400} onChange={event => setEditing({ ...editing, responsibilities: event.target.value.split('\n') })} /></Field>
      <Field id="job-requirements" label="Desired profile · one requirement per line"><textarea id="job-requirements" value={editing.requirements.join('\n')} rows={3} maxLength={2400} onChange={event => setEditing({ ...editing, requirements: event.target.value.split('\n') })} /></Field>
      <label className={s.checkbox}><input type="checkbox" checked={editing.cvRequired} onChange={event => setEditing({ ...editing, cvRequired: event.target.checked })} />CV required for this role</label><p className={s.helper}>A recent profile photo is required. Candidates cannot submit without one.</p>
      <div className={s.sectionHeading}><div><h2>Role questions</h2><p>Only relevant questions. Reorder with the arrow buttons.</p></div><button type="button" className={s.secondary} onClick={() => setEditing({ ...editing, questions: [...editing.questions, { id: `q-${Date.now()}-${editing.questions.length}`, label: '', kind: 'text', required: true }] })}>＋ Add question</button></div>
      {editing.questions.map((q, index) => <section className={s.questionEditor} key={q.id}>
        <div className={s.sectionHeading}><strong>Question {index + 1}</strong><div className={s.inlineActions}><button type="button" className={s.iconButton} disabled={index === 0} aria-label={`Move question ${index + 1} up`} onClick={() => moveQuestion(index, -1)}>↑</button><button type="button" className={s.iconButton} disabled={index === editing.questions.length - 1} aria-label={`Move question ${index + 1} down`} onClick={() => moveQuestion(index, 1)}>↓</button><button type="button" className={s.textButton} onClick={() => setEditing({ ...editing, questions: editing.questions.filter(item => item.id !== q.id).map(item => item.when?.questionId === q.id ? { ...item, when: undefined } : item) })}>Remove</button></div></div>
        <Field id={`label-${q.id}`} label="Question"><input id={`label-${q.id}`} value={q.label} maxLength={240} onChange={event => patchQuestion(index, { label: event.target.value })} /></Field>
        <div className={s.twoColumns}><Field id={`kind-${q.id}`} label="Answer type"><select id={`kind-${q.id}`} value={q.kind} onChange={event => { const kind = event.target.value as QuestionKind; patchQuestion(index, { kind, options: ['select', 'multiselect'].includes(kind) ? q.options || ['Option 1', 'Option 2'] : undefined }); }}><option value="text">Short text</option><option value="textarea">Paragraph</option><option value="number">Number</option><option value="select">Dropdown</option><option value="multiselect">Multiple choice</option><option value="yesno">Yes / No</option></select></Field><label className={s.checkbox}><input type="checkbox" checked={q.required} onChange={event => patchQuestion(index, { required: event.target.checked })} />Required answer</label></div>
        {['select', 'multiselect'].includes(q.kind) && <Field id={`options-${q.id}`} label="Options · one per line"><textarea id={`options-${q.id}`} rows={3} value={q.options?.join('\n') || ''} onChange={event => patchQuestion(index, { options: event.target.value.split('\n') })} /></Field>}
        <Field id={`condition-${q.id}`} label="When to show this question"><select id={`condition-${q.id}`} value={q.when?.questionId || ''} onChange={event => patchQuestion(index, { when: event.target.value ? { questionId: event.target.value, value: 'Yes' } : undefined })}><option value="">Always</option>{editing.questions.slice(0, index).filter(item => item.kind === 'yesno').map(item => <option key={item.id} value={item.id}>When “{item.label}” is Yes</option>)}</select></Field>
      </section>)}
      <div className={s.formActions}><button type="button" className={s.secondary} onClick={() => setEditing(null)}>Cancel</button><button type="button" className={s.primary} onClick={saveVacancy}>Save in preview →</button></div><p className={s.helper}>A new form version applies to future preview applications. Existing submissions keep their original questions and answers.</p>
    </section>}
    {tab === 'settings' && <div className={s.detailGrid}>
      <section className={s.reviewCard}><h2>Careers email</h2><p>Choose the address DEMAC will use. No email is sent or configuration changed in this preview.</p><Field id="careers-sender" label="From address"><input id="careers-sender" type="email" value={sender} placeholder="Choose your Careers email" onChange={event => setSender(event.target.value)} /></Field><Field id="careers-reply" label="Reply-to address"><input id="careers-reply" type="email" value={replyTo} placeholder="Where candidates should reply" onChange={event => setReplyTo(event.target.value)} /></Field><p className={s.helper}>Activation requires approved sender, verified domain, delivery service and durable queue.</p><span className={s.badge}>Not connected · Preview only</span></section>
      <section className={s.reviewCard}><span className={s.eyebrow}>MESSAGE PREVIEW</span><h2>We received your application — DEMAC</h2><p><strong>From:</strong> {sender || 'Sender not selected'}</p><p><strong>Reply to:</strong> {replyTo || sender || 'Not selected'}</p><hr /><p>Hello {'{{firstName}}'},</p><p>Thank you for your interest in DEMAC Professional Cooling Solutions. We have received your application for {'{{jobTitle}}'}, reference {'{{applicationReference}}'}.</p><p>Our team will review your information and contact you if your application moves to the next stage.</p><p>DEMAC Recruitment Team</p><small>Template text, not an actual receipt or sent message.</small></section>
    </div>}
  </section>;
}
