const { TIME_ZONE } = require("./operatingCalendarService");

const VAN_SCHEDULE_FUNCTION_NAME = "sendDailyTechnicianSchedules";
const VAN_SCHEDULE_REGION = "us-central1";
const VAN_SCHEDULE_TIME_ZONE = TIME_ZONE;
const VAN_SCHEDULE_CRON = "0,5,10 8 * * *";
const VAN_SCHEDULE_SCHEDULER_JOB = `firebase-schedule-${VAN_SCHEDULE_FUNCTION_NAME}-${VAN_SCHEDULE_REGION}`;
const VAN_SCHEDULE_DELIVERY_MODEL = "van-group-work-order-v1";
const VAN_SCHEDULE_AUTOMATIC_REASON = "daily-van-schedule";
const VAN_SCHEDULE_AUTOMATIC_DELIVERY_KEY = "auto";

module.exports = {
  VAN_SCHEDULE_AUTOMATIC_DELIVERY_KEY,
  VAN_SCHEDULE_AUTOMATIC_REASON,
  VAN_SCHEDULE_CRON,
  VAN_SCHEDULE_DELIVERY_MODEL,
  VAN_SCHEDULE_FUNCTION_NAME,
  VAN_SCHEDULE_REGION,
  VAN_SCHEDULE_SCHEDULER_JOB,
  VAN_SCHEDULE_TIME_ZONE,
};
