'use client';
import { Suspense, cloneElement, isValidElement, useId, useCallback, useEffect, useRef, useState, type ReactElement, type ReactNode } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '../auth/auth-provider';
import { careersAdmin, newRequestId, newVacancy, newQuestion, downloadApplicantDocument, type RecruitmentVacancy, type ApplicantSummary, type ApplicantRecord, type CareersSettings, type Page, type DocumentRecord } from '../../lib/firebase/careers';
import { stages, type QuestionKind } from '../../lib/careers-preview';
import s from './recruitment.module.css';
function Field({ label, children }: { label: string; children: ReactNode }) {
  const id = useId();
  return <div className={s.field}><label htmlFor={id}>{label}</label>{isValidElement(children) ? cloneElement(children as ReactElement<{ id?: string }>, { id }) : children}</div>;
}
function Back({ onClick }: { onClick: () => void }) { return <button type="button" className={s.round} onClick={onClick} aria-label="Back to list" title="Back to list"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg></button>; }
const err = (e: unknown) => e instanceof Error ? e.message : 'This action could not be completed.';
const stamp = (value: string) => new Date(value).toLocaleString('en-GB', { timeZone: 'America/Aruba', dateStyle: 'medium', timeStyle: 'short' });
function Workspace() {
  const { principal } = useAuth();
  const router = useRouter(), params = useSearchParams();
  const rawTab = params.get('tab'), tab = rawTab === 'applicants' || rawTab === 'settings' ? rawTab : 'vacancies', edit = params.get('edit'), candidate = params.get('candidate');
  const [jobs, setJobs] = useState<RecruitmentVacancy[]>([]), [applicants, setApplicants] = useState<ApplicantSummary[]>([]);
  const [vacancy, setVacancy] = useState<RecruitmentVacancy | null>(null), [profile, setProfile] = useState<ApplicantRecord | null>(null);
  const [settings, setSettings] = useState<CareersSettings | null>(null), [blockers, setBlockers] = useState<string[]>([]);
  const [loading, setLoading] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [search, setSearch] = useState(''), [filter, setFilter] = useState(''), [minimum, setMinimum] = useState(''), [cursor, setCursor] = useState<string | null>(null), [note, setNote] = useState('');
  const [photo, setPhoto] = useState('');
  const seq = useRef(0);
  const mutation = useRef<{ body: string; id: string } | null>(null);
  const to = (next: string, values: Record<string, string> = {}) => router.push(`/recruitment/?${new URLSearchParams({ tab: next, ...values })}`);
  function requestId(payload: unknown) { const body = JSON.stringify(payload); if (mutation.current?.body !== body) mutation.current = { body, id: newRequestId() }; return mutation.current.id; }
  const load = useCallback(async (nextCursor?: string) => {
    const ticket = ++seq.current;
    setError(''); setLoading(true);
    try {
      if (tab === 'settings') {
        const data = await careersAdmin<{ settings: CareersSettings | null; blockers: string[] }>('settings.get');
        if (ticket !== seq.current) return;
        setSettings(data.settings || { version: 0, intakeEnabled: false, privacyText: '', privacyVersion: '', retentionDays: 0, talentRetentionDays: 0, from: '', replyTo: '', senderName: 'DEMAC Recruitment' }); setBlockers(data.blockers);
      } else if (tab === 'applicants' && candidate) {
        const data = await careersAdmin<ApplicantRecord>('applications.get', { id: candidate }); if (ticket === seq.current) { setProfile(data); setNote(''); }
      } else if (tab === 'vacancies' && edit) {
        const data = edit === 'new' ? newVacancy() : await careersAdmin<RecruitmentVacancy>('vacancies.get', { id: edit }); if (ticket === seq.current) setVacancy(data);
      } else {
        const data = await careersAdmin<Page<RecruitmentVacancy | ApplicantSummary>>(tab === 'applicants' ? 'applications.list' : 'vacancies.list', { search, ...(tab === 'applicants' ? { stage: filter, minExperience: minimum } : { status: filter }), cursor: nextCursor || null, limit: 25 });
        if (ticket !== seq.current) return;
        if (tab === 'applicants') setApplicants(previous => nextCursor ? [...previous, ...data.items as ApplicantSummary[]] : data.items as ApplicantSummary[]);
        else setJobs(previous => nextCursor ? [...previous, ...data.items as RecruitmentVacancy[]] : data.items as RecruitmentVacancy[]);
        setCursor(data.nextCursor);
      }
    } catch (e) { if (ticket === seq.current) setError(err(e)); }
    finally { if (ticket === seq.current) setLoading(false); }
  }, [tab, edit, candidate, search, filter, minimum]);
  useEffect(() => { setNotice(''); setVacancy(null); setProfile(null); void load(); }, [tab, edit, candidate]);
  useEffect(() => {
    setPhoto(''); let disposed = false, url = '';
    const file = profile?.documents.find(d => d.kind === 'photo');
    if (profile && file) void downloadApplicantDocument(profile.id, file).then(blob => { url = URL.createObjectURL(blob); if (!disposed) setPhoto(url); else URL.revokeObjectURL(url); }).catch(() => {});
    return () => { disposed = true; if (url) URL.revokeObjectURL(url); };
  }, [profile?.id]);
  if (!principal.active || principal.role !== 'super_admin') return <section className={s.root}><div className={s.notice}>Recruitment is restricted to authorized DEMAC administrators.</div></section>;
  async function perform(action: string, payload: Record<string, unknown>, success: string, after?: () => void) {
    if (saving) return; setSaving(true); setError(''); setNotice('');
    try { await careersAdmin(action, { ...payload, requestId: requestId(payload) }); mutation.current = null; setNotice(success); if (after) after(); else await load(); }
    catch (e) { setError(err(e)); } finally { setSaving(false); }
  }
  async function download(file: DocumentRecord) {
    if (!profile) return; setSaving(true);
    try { const blob = await downloadApplicantDocument(profile.id, file), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = file.name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 60000); }
    catch (e) { setError(err(e)); } finally { setSaving(false); }
  }
  const v = vacancy;
  return <section className={s.root} aria-label="Recruitment administration">
    <header className={s.head}><div><div className={s.muted}>MANAGEMENT / PEOPLE</div><h1>Recruitment</h1><p>Manage opportunities, application forms and candidates.</p></div>{tab === 'vacancies' && !edit && <button className={s.primary} onClick={() => to('vacancies', { edit: 'new' })}>＋ New vacancy</button>}</header>
    <nav className={s.tabs} aria-label="Recruitment navigation">{[['vacancies', 'Vacancies'], ['applicants', 'Applicants'], ['settings', 'Settings']].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => { setFilter(''); setSearch(''); to(value); }}>{label}</button>)}</nav>
    {error && <div className={s.error} role="alert">{error}<div className={s.actions}><button onClick={() => void load()}>Reload</button></div></div>}
    {notice && <div className={s.notice} role="status">{notice}</div>}
    {loading && <p role="status" className={s.muted}>Loading from DEMAC…</p>}
    {((tab === 'vacancies' && !edit) || (tab === 'applicants' && !candidate)) && <>
      <form className={s.filters} onSubmit={e => { e.preventDefault(); void load(); }}><Field label="Search"><input value={search} onChange={e => setSearch(e.target.value)} placeholder={tab === 'applicants' ? 'Name, role or skills' : 'Position or department'} /></Field><Field label={tab === 'applicants' ? 'Stage' : 'Status'}><select value={filter} onChange={e => setFilter(e.target.value)}><option value="">All</option>{(tab === 'applicants' ? stages : ['Draft', 'Open', 'Paused', 'Closed', 'Archived']).map(status => <option key={status}>{status}</option>)}</select></Field>{tab === 'applicants' ? <Field label="Minimum experience"><input type="number" min="0" max="70" value={minimum} onChange={e => setMinimum(e.target.value)} /></Field> : <span />}<button disabled={loading}>Apply filters</button></form>
      <div className={s.panel}>{tab === 'vacancies' ? jobs.map(job => <div className={s.row} key={job.id}><div><strong>{job.title}</strong><small>{job.department} · {job.location} · {job.contract}</small><small>{job.questions.length} questions · Form version {job.version}</small></div><div className={s.rowActions}><span className={s.pill}>{job.status}</span><button onClick={() => to('vacancies', { edit: job.id })}>Edit position</button></div></div>) : applicants.map(person => <div className={s.row} key={person.id}><div><strong>{person.name}</strong><small>{person.title} · {person.experience} years · {person.country}</small><small>{stamp(person.createdAt)}</small></div><div className={s.rowActions}><span className={s.pill}>{person.stage}</span><button onClick={() => to('applicants', { candidate: person.id })}>Open profile</button></div></div>)}{!loading && !error && !(tab === 'vacancies' ? jobs.length : applicants.length) && <div className={s.empty}>No matching records on this page.{!cursor && tab === 'vacancies' && ' Create your first vacancy to get started.'}</div>}{cursor && <div className={s.actions}><button disabled={loading} onClick={() => void load(cursor)}>Load next results</button></div>}</div>
    </>}
    {tab === 'vacancies' && edit && v && <form onSubmit={e => { e.preventDefault(); void perform('vacancies.save', { id: v.id, expectedVersion: v.version, vacancy: v }, 'Vacancy saved in DEMAC.', () => to('vacancies')); }}>
      <div className={s.head}><Back onClick={() => to('vacancies')} /><strong>{v.version ? 'Edit vacancy' : 'Create vacancy'} · {v.title || 'New position'}</strong></div>
      <fieldset disabled={saving} style={{ border: 0, padding: 0, minWidth: 0 }}>
      <section className={s.panel}><h2>1. Position details</h2><div className={s.grid}>{(['title', 'department', 'location', 'contract'] as const).map(key => <Field key={key} label={({ title: 'Job title', department: 'Department', location: 'Location', contract: 'Employment type' })[key]}><input required value={v[key]} maxLength={key === 'department' || key === 'contract' ? 80 : 100} onChange={e => setVacancy({ ...v, [key]: e.target.value })} /></Field>)}<Field label="Available positions"><input type="number" required min="1" max="100" value={v.openings} onChange={e => setVacancy({ ...v, openings: Number(e.target.value) })} /></Field><Field label="Publication status"><select value={v.status} onChange={e => setVacancy({ ...v, status: e.target.value as RecruitmentVacancy['status'] })}>{['Draft', 'Open', 'Paused', 'Closed', 'Archived'].map(status => <option key={status}>{status}</option>)}</select></Field><Field label="Publication date (optional)"><input type="date" value={v.publishFrom || ''} onChange={e => setVacancy({ ...v, publishFrom: e.target.value || null })} /></Field><Field label="Closing date (optional)"><input type="date" value={v.publishUntil || ''} onChange={e => setVacancy({ ...v, publishUntil: e.target.value || null })} /></Field></div></section>
      <section className={s.panel}><h2>2. Role information & desired profile</h2><Field label="About the role"><textarea required maxLength={1500} value={v.summary} onChange={e => setVacancy({ ...v, summary: e.target.value })} /></Field>{(['responsibilities', 'requirements', 'desired'] as const).map(key => <Field key={key} label={({ responsibilities: 'Responsibilities — one per line', requirements: 'Essential requirements — one per line', desired: 'Preferred qualifications — one per line' })[key]}><textarea value={v[key].join('\n')} onChange={e => setVacancy({ ...v, [key]: e.target.value.split('\n') })} /></Field>)}<Field label="Internal hiring notes — never shown to applicants"><textarea maxLength={3000} value={v.internalNotes} onChange={e => setVacancy({ ...v, internalNotes: e.target.value })} /></Field></section>
      <section className={s.panel}><h2>3. Application form</h2><div className={s.notice}>The candidate completes: contact details → role questions → recent photo and documents. Name, email, phone and the approved administrative fields are collected by the standard form.</div><label className={s.check}><input type="checkbox" checked={v.cvRequired} onChange={e => setVacancy({ ...v, cvRequired: e.target.checked })} />CV required for this position</label><p className={s.muted}>Recent profile photo required. Additional certificates are optional. The photo is not used for automated scoring.</p>
      {v.questions.map((q, index) => { const change = (patch: Partial<typeof q>) => setVacancy({ ...v, questions: v.questions.map((item, at) => at === index ? { ...item, ...patch } : item) }); return <div className={s.question} key={q.id}><div className={s.head}><strong>Question {index + 1}</strong><div className={s.rowActions}><button type="button" disabled={!index} aria-label={`Move question ${index + 1} up`} onClick={() => { const qs = [...v.questions]; [qs[index - 1], qs[index]] = [qs[index], qs[index - 1]]; setVacancy({ ...v, questions: qs }); }}>↑</button><button type="button" onClick={() => setVacancy({ ...v, questions: v.questions.filter(item => item.id !== q.id).map(item => item.when?.questionId === q.id ? { ...item, when: undefined } : item) })}>Remove</button></div></div><Field label="Question"><input required value={q.label} maxLength={240} onChange={e => change({ label: e.target.value })} /></Field><div className={s.grid}><Field label="Answer format"><select value={q.kind} onChange={e => change({ kind: e.target.value as QuestionKind, options: ['select', 'multiselect'].includes(e.target.value) ? q.options || [] : undefined })}><option value="text">Short answer</option><option value="textarea">Paragraph</option><option value="number">Number</option><option value="select">Dropdown</option><option value="multiselect">Multiple choice</option><option value="yesno">Yes / No</option></select></Field><label className={s.check}><input type="checkbox" checked={q.required} onChange={e => change({ required: e.target.checked })} />Required answer</label></div>{['select', 'multiselect'].includes(q.kind) && <Field label="Available answers — one per line"><textarea value={(q.options || []).join('\n')} onChange={e => change({ options: e.target.value.split('\n') })} /></Field>}<Field label="Visibility"><select value={q.when?.questionId || ''} onChange={e => change({ when: e.target.value ? { questionId: e.target.value, value: 'Yes' } : undefined })}><option value="">Always show</option>{v.questions.slice(0, index).filter(item => item.kind === 'yesno').map(item => <option key={item.id} value={item.id}>When “{item.label}” is Yes</option>)}</select></Field></div>; })}<div className={s.actions}><button type="button" disabled={v.questions.length >= 30} onClick={() => setVacancy({ ...v, questions: [...v.questions, newQuestion()] })}>＋ Add role question</button></div></section>
      <div className={s.actions}><button type="button" onClick={() => to('vacancies')}>Cancel</button><button className={s.primary} type="submit">{saving ? 'Saving…' : v.status === 'Open' ? 'Save & open vacancy' : 'Save vacancy'}</button></div></fieldset>
    </form>}
    {tab === 'applicants' && candidate && profile && <>
      <div className={s.head}><Back onClick={() => to('applicants')} /><span className={s.pill}>{profile.reference}</span></div><section className={s.panel}><div className={s.profileHead}>{photo && <img className={s.photo} src={photo} alt="Candidate profile photo" />}<div><h2>{profile.profile.givenName} {profile.profile.familyName}</h2><p>{profile.jobSnapshot.title}</p><small className={s.muted}>{stamp(profile.createdAt)} · Form version {profile.jobSnapshot.version}</small></div></div><div className={s.actions}><select aria-label="Recruitment stage" style={{ maxWidth: 220 }} disabled={saving} value={profile.stage} onChange={e => void perform('applications.update', { id: profile.id, expectedVersion: profile.version, stage: e.target.value }, 'Selection stage updated. No automated message was sent.')}>{stages.map(stage => <option key={stage}>{stage}</option>)}</select></div></section>
      <div className={s.grid}><section className={s.panel}><h2>Contact information</h2><dl className={s.answers}>{[['Email', profile.profile.email], ['Phone', `${profile.profile.dialCode} ${profile.profile.phone}`], ['Residence', `${profile.profile.city}, ${profile.profile.residence}`], ['Nationality — administrative', profile.profile.nationality], ['Experience', `${profile.profile.relevantExperience} relevant / ${profile.profile.totalExperience} total years`], ['Languages', profile.profile.languages.join(', ')], ['Availability', profile.profile.availability]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className={s.panel}><h2>Role answers</h2><dl className={s.answers}>{profile.jobSnapshot.questions.map(q => <div key={q.id}><dt>{q.label}</dt><dd>{Array.isArray(profile.profile.answers[q.id]) ? (profile.profile.answers[q.id] as string[]).join(', ') : profile.profile.answers[q.id] || 'Not provided'}</dd></div>)}</dl></section><section className={s.panel}><h2>Private documents</h2>{profile.documents.map(file => <div key={file.id} className={s.row}><div><strong>{file.name}</strong><small>{file.kind} · {(file.size / 1024).toFixed(0)} KB</small></div><button disabled={saving} onClick={() => void download(file)}>Download</button></div>)}<p className={s.muted}>Confirmation email status: {profile.emailStatus}. SMTP acceptance is not proof of delivery.</p></section><section className={s.panel}><h2>Recruiter notes</h2><div className={s.stack}>{profile.notes.map(n => <div className={s.note} key={n.id}><small>{n.actorName} · {stamp(n.at)}</small><p>{n.text}</p></div>)}</div><Field label="Private note"><textarea value={note} maxLength={2000} onChange={e => setNote(e.target.value)} /></Field><button disabled={saving || !note.trim()} onClick={() => void perform('applications.update', { id: profile.id, expectedVersion: profile.version, note }, 'Note saved.')}>Save note</button></section></div><section className={s.panel}><h2>Application activity</h2>{profile.events.map(event => <div className={s.row} key={event.id}><strong>{event.action}</strong><small>{stamp(event.at)}</small></div>)}</section>
    </>}
    {tab === 'settings' && settings && <form onSubmit={e => { e.preventDefault(); void perform('settings.save', { settings, expectedVersion: settings.version }, 'Careers settings saved.'); }}><fieldset disabled={saving} style={{ border: 0, padding: 0, minWidth: 0 }}>
      {!!blockers.length && <div className={s.notice}><strong>Before accepting applications</strong>{blockers.map(b => <p key={b}>{b}</p>)}</div>}
      <section className={s.panel}><h2>Careers email</h2><div className={s.grid}><Field label="From address — chosen and verified by DEMAC"><input type="email" required value={settings.from} onChange={e => setSettings({ ...settings, from: e.target.value })} /></Field><Field label="Reply-to address"><input type="email" required value={settings.replyTo} onChange={e => setSettings({ ...settings, replyTo: e.target.value })} /></Field><Field label="Sender name"><input required value={settings.senderName} onChange={e => setSettings({ ...settings, senderName: e.target.value })} /></Field></div><p className={s.muted}>Credentials are configured securely on the server, never in this screen. The automatic email acknowledges receipt, not hiring.</p></section>
      <section className={s.panel}><h2>Privacy & retention</h2><Field label="Approved recruitment privacy notice"><textarea required rows={7} value={settings.privacyText} onChange={e => setSettings({ ...settings, privacyText: e.target.value })} /></Field><div className={s.grid}><Field label="Notice version"><input required value={settings.privacyVersion} onChange={e => setSettings({ ...settings, privacyVersion: e.target.value })} /></Field><Field label="Application retention (days)"><input required type="number" min="1" max="730" value={settings.retentionDays || ''} onChange={e => setSettings({ ...settings, retentionDays: Number(e.target.value) })} /></Field><Field label="Future-opportunity opt-in retention (days)"><input required type="number" min="1" max="730" value={settings.talentRetentionDays || ''} onChange={e => setSettings({ ...settings, talentRetentionDays: Number(e.target.value) })} /></Field></div></section>
      <section className={s.panel}><h2>Application intake</h2><label className={s.check}><input type="checkbox" checked={settings.intakeEnabled} onChange={e => setSettings({ ...settings, intakeEnabled: e.target.checked })} />Accept applications for open vacancies</label><p className={s.muted}>Opening intake requires verified server configuration. Pausing it does not delete vacancies or applicants.</p><div className={s.actions}><button type="button" disabled={!settings.version} onClick={() => void perform('settings.verify', {}, 'Server email and antivirus connection checks completed. No email was sent.')}>Verify saved setup</button><button className={s.primary} type="submit">{saving ? 'Saving…' : 'Save settings'}</button></div></section>
    </fieldset></form>}
  </section>;
}
export function RecruitmentWorkspace() { return <Suspense fallback={<p>Loading Recruitment…</p>}><Workspace /></Suspense>; }
