import { maintenance } from '@/lib/revenue-cycle';

export default function MaintenancePage() {
  return <div className="rc-stack">
    <section className="page-head"><div><div className="eyebrow">Retention · Asset Lifecycle</div><h1>Maintenance & Agreements</h1><p>Recurring service obligations stay connected to the customer, property and individual HVAC asset so follow-up becomes proactive instead of manual memory.</p></div><div className="page-actions"><button className="btn" type="button">Agreement Templates</button><button className="btn primary" type="button">+ Maintenance Plan</button></div></section>
    <section className="rc-metrics"><article><span>Due in 14 Days</span><strong>23</strong><small>Service opportunities</small></article><article><span>Overdue</span><strong>6</strong><small className="rc-warn">Needs follow-up</small></article><article><span>Active Agreements</span><strong>18</strong><small>Residential + commercial</small></article><article><span>Renewal Value</span><strong>Afl. 31.4K</strong><small className="rc-good">Next 90 days</small></article></section>
    <section className="panel rc-table-panel"><header className="panel-head"><div><h2>Maintenance Queue</h2><span>Asset-level due dates and contract opportunities</span></div><span>Next 30 days</span></header><div className="rc-table rc-maint-table"><div className="rc-row rc-head"><span>Customer / Asset</span><span>Due</span><span>Interval</span><span>Status</span><span>Value</span><span>Last Service</span></div>{maintenance.map(item=><div className="rc-row" key={`${item.customer}-${item.asset}`}><div><strong>{item.customer}</strong><small>{item.asset}</small></div><time>{item.due}</time><span>{item.interval}</span><b className={item.status==='Overdue'?'rc-danger':''}>{item.status}</b><strong>{item.value}</strong><span>{item.last}</span></div>)}</div></section>
    <section className="rc-two-col"><article className="panel"><header className="panel-head"><div><h2>Renewal Engine</h2><span>Controlled operational messaging</span></div></header><div className="rc-flow"><strong>Maintenance Window</strong><i>→</i><strong>Follow-up Task</strong><i>→</i><strong>Customer Response</strong><i>→</i><strong>Valid Slot</strong><i>→</i><strong>Work Order</strong></div></article><article className="panel"><header className="panel-head"><div><h2>Retention Signals</h2><span>Customers drifting from normal service cycle</span></div></header><div className="rc-rule-list"><div><strong>Asset due</strong><span>Use actual last service and configured interval.</span></div><div><strong>Inactive customer</strong><span>Flag when the normal service cadence is exceeded.</span></div><div><strong>Consent</strong><span>Maintenance reminders remain service-related operational communication.</span></div></div></article></section>
  </div>;
}
