import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { FieldDayOverview } from '../components/field/field-day-overview';
import { FieldPortalNavigation, FieldPortalHeader, FieldJobContext, FieldPortalIdentity, fieldPortalStyles as styles } from '../components/field/field-portal-chrome';
const one = { id:'DEMO-WO1',workOrderId:'DEMO-WO1',appointmentId:'DEMO-APT1',date:'2026-09-23',time:'10:30',endTime:'12:30',status:'Confirmada',customerId:'DEMO-C1',customerName:'DEMO · Cliente de prueba',propertyId:'DEMO-P1',propertyName:'DEMO · Apartamento 07',address:'Dirección sintética de prueba',plannedWork:[{id:'DEMO-LINE',label:'Standard Service',quantity:2}],estimatedQuantity:2,vanId:'DEMO-VAN1',responsibility:'lead',assignmentSource:'daily_assignment',allowedActions:['read'],fieldVisit:null,canPrepareVisit:true,canCreateReturnVisit:false,locationSnapshot:{accessContact:{name:'DEMO · Contacto',phone:''},locationLabel:'DEMO · Apartamento 07',accessInstructions:''},crew:{vanId:'DEMO-VAN1',vanName:'DEMO · Van 1',members:[{staffId:'DEMO-TECH',name:'DEMO · Técnico',responsibility:'lead'},{staffId:'DEMO-HELPER',name:'DEMO · Ayudante',responsibility:'helper'}]}} as any;
const jobs=[{...one,id:'DEMO-DONE',workOrderId:'DEMO-DONE',time:'08:30',endTime:'09:30',status:'Completada',propertyName:'DEMO · Casa principal'},one,{...one,id:'DEMO-LATER',workOrderId:'DEMO-LATER',time:'13:30',endTime:'14:30',propertyName:'DEMO · Restaurante',plannedWork:[{id:'DEMO-OTHER',label:'Check-up',quantity:1}]}];
const events: string[]=[];(window as any).events=events;
function App(){ const [tab,setTab]=useState<any>('home');const [selected,setSelected]=useState<any>(null); const mode=(window as any).testMode;
 return <>{selected ? <div className={styles.portal}><FieldPortalHeader title="Trabajo en curso" onBack={()=>setSelected(null)} /><main className={styles.surface}><FieldJobContext job={selected}/><FieldPortalIdentity name="DEMO · Técnico" staffId="DEMO-TECH" date={one.date} job={selected} compact /><div className={styles.notice}>Prueba de componente: el flujo completo usa la autoridad Field existente.</div></main></div>:<FieldDayOverview tab={tab} identity={{displayName:'DEMO · Técnico',staffId:'DEMO-TECH'}} date={one.date} jobs={mode==='error'||mode==='empty'||mode==='loading'?[]:jobs} nextJob={mode==='error'||mode==='empty'||mode==='loading'?null:one} loading={mode==='loading'} error={mode==='error'?'Error sintético de conexión.':null} stale={mode==='offline'} onRetry={()=>events.push('retry')} onOpen={(id)=>{events.push('open:'+id);setSelected(jobs.find(x=>x.workOrderId===id));}} onNavigate={setTab} onSignOut={()=>events.push('signout')}/>}<FieldPortalNavigation active={selected?'jobs':tab} onNavigate={(tab)=>{setTab(tab);setSelected(null);}}/></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
