import { expenseItems } from '@/lib/revenue-cycle';

export default function ExpensesPage() {
  return <div className="rc-stack">
    <section className="page-head"><div><div className="eyebrow">Finance · Purchase Intelligence</div><h1>Expenses & Budgets</h1><p>Voice and document-assisted purchase capture can classify costs, receive inventory/tools, retain evidence and update budget pace from one controlled transaction.</p></div><div className="page-actions"><button className="btn" type="button">Budget Categories</button><button className="btn primary" type="button">+ Capture Expense</button></div></section>
    <section className="rc-metrics"><article><span>Month Spend</span><strong>Afl. 40.5K</strong><small>81% of Afl. 50K budget</small></article><article><span>Spend Pace Risk</span><strong>+46 pts</strong><small className="rc-danger-text">Ahead of elapsed month</small></article><article><span>Awaiting Evidence</span><strong>3</strong><small className="rc-warn">Missing receipt / invoice</small></article><article><span>Auto Classified</span><strong>89%</strong><small className="rc-good">Preview confidence</small></article></section>
    <section className="rc-two-col rc-expense-capture"><article className="panel"><header className="panel-head"><div><h2>AI Purchase Capture</h2><span>Speak first, verify against evidence</span></div></header><div className="rc-voice-box"><div className="rc-mic">●</div><div><strong>“100 florins new drill battery, 50 screws, 50 wiring, 20 switches...”</strong><span>AI proposes line items and classifications using the controlled Item Master.</span></div></div><div className="rc-capture-flow"><strong>Voice</strong><i>+</i><strong>Receipt / Invoice</strong><i>→</i><strong>Structured Lines</strong><i>→</i><strong>Review</strong><i>→</i><strong>Expense + Inventory</strong></div></article><article className="panel"><header className="panel-head"><div><h2>Budget Pace</h2><span>Management warning before month-end</span></div></header><div className="rc-budget-meter"><div><span>Month elapsed</span><strong>35%</strong></div><div className="rc-budget-track"><i className="time" style={{width:'35%'}}/><i className="spend" style={{width:'81%'}}/></div><div><span>Actual spend</span><strong className="rc-danger-text">81%</strong></div><p>At the current run-rate, expenses project around Afl. 61K versus the Afl. 50K working budget.</p></div></article></section>
    <section className="panel rc-table-panel"><header className="panel-head"><div><h2>Recent Expense Evidence</h2><span>Invoice is authoritative monetary evidence when voice and document disagree</span></div></header><div className="rc-table rc-expense-table"><div className="rc-row rc-head"><span>Vendor / Description</span><span>Category</span><span>Total</span><span>Evidence</span><span>Status</span></div>{expenseItems.map(item=><div className="rc-row" key={`${item.vendor}-${item.description}`}><div><strong>{item.vendor}</strong><small>{item.description}</small></div><span>{item.category}</span><strong>{item.total}</strong><span>{item.evidence}</span><b>{item.status}</b></div>)}</div></section>
  </div>;
}
