const fs=require('node:fs'),assert=require('node:assert/strict');
const base=process.env.PREVIEW_URL||'http://127.0.0.1:4397';if(!/^http:\/\/127\.0\.0\.1:4397$/.test(base)&&!/^https:\/\/[a-z0-9-]+\.trycloudflare\.com$/.test(base))throw Error('Synthetic gateway only');
const creds=JSON.parse(fs.readFileSync(process.env.PREVIEW_CREDENTIALS_FILE,'utf8'));const created=JSON.parse(fs.readFileSync(process.env.PREVIEW_EVIDENCE_DIR+'/booking-result.json','utf8'));
const project='demo-demac-dwellings';const path='/__preview/firebase/us-central1-'+project+'.cloudfunctions.net/';
async function auth(email){const r=await fetch(base+'/__preview/firebase/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:creds.password,returnSecureToken:true})});assert.equal(r.status,200);return(await r.json()).idToken}
async function call(endpoint,token,action,data={}){const r=await fetch(base+path+endpoint,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify({action,data})});return {status:r.status,body:await r.json()}}
(async()=>{
const office=await auth(creds.office),tech=await auth(creds.technician);
for(const token of ['',office+'forged'])assert.equal((await call('officeBookingAuthority',token,'list_property_locations',{})).status,401);
const denied=await call('officeBookingAuthority',tech,'save_property_locations',{customerId:created.appointment.customerId,propertyId:created.appointment.propertyId});assert.equal(denied.status,403);
assert.equal((await call('officeBookingAuthority',office,'send_appointment_reminder',{})).status,403);
for(const [url,method]of [['/__preview/firebase/firestore.googleapis.com/v1/projects/demac-corporation/databases/(default)/documents/clients','GET'],['/__preview/firebase/firestore.googleapis.com/v1/projects/demo-demac-dwellings/databases/(default)/documents/clients/INVALID','PATCH'],['/__preview/firebase/firebasestorage.googleapis.com/v0/b/demac-corporation/o','GET']])assert.equal((await fetch(base+url,{method,headers:{authorization:'Bearer '+office}})).status,403);
console.log('PASS gateway unauthenticated/forged token, technician writes, production destinations, direct writes and external delivery denied');
const workOrderId=created.workOrderIds[0];const get=await call('fieldOperationsAuthority',tech,'get_job',{workOrderId});assert.equal(get.status,200,JSON.stringify(get));assert.equal(get.body.job.dwellingId,created.appointment.dwellingId);assert.equal(get.body.job.locationSnapshot.accessContact.name,'DEMO Access contact');console.log('PASS real technician authenticated and assigned job retains dwelling, requester/access');
const prepared=await call('fieldOperationsAuthority',tech,'prepare_visit',{workOrderId,requestId:'dwellings-live-prepare'});assert.equal(prepared.status,200,JSON.stringify(prepared));let visit=prepared.body.visit;
for(const target of ['en_route','on_site']){if(['on_site','in_progress'].includes(visit.status))break;const transition=await call('fieldOperationsAuthority',tech,'transition_visit',{visitId:visit.id,to:target,expectedVersion:visit.version,requestId:'dwellings-live-'+target});assert.equal(transition.status,200,JSON.stringify(transition));visit=transition.body.visit}
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aK1cAAAAASUVORK5CYII=','base64');const paths={};
for(const kind of ['equipment_reference','indoor_nameplate','outdoor_nameplate']){paths[kind]='field-evidence/'+visit.id+'/dwellings-test/'+kind+'.png';const uploaded=await fetch(base+'/__preview/firebase/firebasestorage.googleapis.com/v0/b/'+project+'.appspot.com/o?uploadType=media&name='+encodeURIComponent(paths[kind]),{method:'POST',headers:{authorization:'Bearer '+tech,'content-type':'image/png'},body:bytes});assert.equal(uploaded.status,200,await uploaded.text())}
const ids=[];for(const [index,btu]of [12000,12000,18000].entries()){const registered=await call('fieldOperationsAuthority',tech,'register_visit_asset',{visitId:visit.id,requestId:'dwellings-live-equipment-'+index,areaId:get.body.job.areas[0].id,locationLabel:'Living room',systemType:'Split',brand:'DEMO',btu,refrigerant:'R32',voltage:'220V',evidencePaths:paths});assert.equal(registered.status,200,JSON.stringify(registered));ids.push(registered.body.equipment.id);const attached=await call('fieldOperationsAuthority',tech,'attach_visit_asset',{visitId:visit.id,requestId:'dwellings-live-attach-'+index,assetId:registered.body.equipment.id});assert.equal(attached.status,200,JSON.stringify(attached))}
assert.equal(new Set(ids).size,3);
const final=await call('fieldOperationsAuthority',tech,'get_job',{workOrderId});assert.equal(final.status,200,JSON.stringify(final));assert.equal(final.body.job.visitAssets.length,3);assert.equal(final.body.job.professionalReportPreview.dwellingId,created.appointment.dwellingId);
fs.writeFileSync(process.env.PREVIEW_EVIDENCE_DIR+'/field-result.json',JSON.stringify(final.body,null,2));console.log('PASS real Field API and Storage: three distinct A/C (two identical), one area, visit assets and report retain dwelling');
})().catch(e=>{console.error(e);process.exitCode=1});
