import { leads } from '@/lib/revenue-cycle';

export default function LeadsPage() {
  return <div className="rc-stack">
    <section className="page-head"><div><div className="eyebrow">CRM · Demand Intake</div><h1>Leads</h1><p>Every new inquiry has a source, owner, qualification state and next action before it becomes an opportunity or customer job.</p></div><div className="page-actions"><button className="btn" type="button">Sources</button><button className="btn primary" type="button">+ Lead</button></div></section>
    <section className="rc-metrics"><article><span>New Today</span><strong>18</strong><small>WhatsApp leads largest source</small></article><article><span>Unassigned</span><strong>3</strong><small className="rc-warn">Needs ownership</small></article><article><span>Qualified</span><strong>11</strong><small className="rc-good">61% qualification rate</small></article><article><span>Booking Conversion</span><strong>38%</strong><small className="rc-good">Above 35% target</small></article></section>
    <section className="panel rc-table-panel"><header className="panel-head"><div><h2>Active Lead Queue</h2><span>Oldest / highest-intent items should never disappear in chat history</span></div><span>{leads.length} preview</span></header><div className="rc-table rc-lead-table"><div className="rc-row rc-head"><span>Lead</span><span>Source</span><span>Stage</span><span>Owner</span><span>Next Action</span><span>Age</span></div>{leads.map(lead=><div className="rc-row" key={lead.name}><div><strong>{lead.name}</strong><small>{lead.request} · {lead.area}</small></div><span>{lead.source}</span><b>{lead.stage}</b><span>{lead.owner}</span><span>{lead.next}</span><time>{lead.age}</time></div>)}</div></section>
    <section className="rc-two-col"><article className="panel"><header className="panel-head"><div><h2>Source Attribution</h2><span>Lead source should follow through to booked revenue and margin</span></div></header><div className="rc-source-list"><div><span>WhatsApp</span><strong>46%</strong><i style={{width:'46%'}}/></div><div><span>Phone</span><strong>24%</strong><i style={{width:'24%'}}/></div><div><span>Referral</span><strong>18%</strong><i style={{width:'18%'}}/></div><div><span>Website / Other</span><strong>12%</strong><i style={{width:'12%'}}/></div></div></article><article className="panel"><header className="panel-head"><div><h2>Lead Rules</h2><span>Commercial memory</span></div></header><div className="rc-rule-list"><div><strong>Recognize existing phone</strong><span>Open Customer 360 instead of creating a duplicate.</span></div><div><strong>Owner + next action</strong><span>No qualified lead can remain ownerless or without a due next step.</span></div><div><strong>Conversion trace</strong><span>Source stays linked through opportunity, estimate, booking and collected revenue.</span></div></div></article></section>
  </div>;
}
