import { tools } from '@/lib/field-assets';

export default function ToolsPage() {
  return <div className="fa-stack">
    <section className="page-head"><div><div className="eyebrow">Company Assets · Custody</div><h1>Tools & Equipment</h1><p>Company tools are controlled assets with identity, custody, condition, calibration and replacement value — separate from sellable inventory.</p></div><div className="page-actions"><button className="btn" type="button">Calibration Due</button><button className="btn primary" type="button">+ Tool</button></div></section>
    <section className="fa-metrics"><article><span>Registered Tools</span><strong>42</strong><small>Across warehouse + vans</small></article><article><span>Assigned to Vans</span><strong>31</strong><small>Named custody</small></article><article><span>Calibration Due</span><strong>2</strong><small className="fa-warn">Next 30 days</small></article><article><span>Lost / Damaged</span><strong>0</strong><small className="fa-good">No open incidents</small></article></section>
    <section className="panel fa-table-panel"><header className="panel-head"><div><h2>Tool Register</h2><span>Identity, custody, condition and service state</span></div><span>QR-ready asset model</span></header><div className="fa-table fa-tool-table"><div className="fa-row fa-head"><span>Asset</span><span>Type</span><span>Custody</span><span>Condition</span><span>Calibration</span><span>Value</span><span>Next Action</span></div>{tools.map(tool=><div className="fa-row" key={tool.id}><div><strong>{tool.name}</strong><small>{tool.id}</small></div><span>{tool.type}</span><strong>{tool.custody}</strong><span>{tool.condition}</span><b className={tool.calibration==='Due Soon'?'warn':''}>{tool.calibration}</b><span>{tool.value}</span><span>{tool.next}</span></div>)}</div></section>
    <section className="fa-two-col"><article className="panel"><header className="panel-head"><div><h2>Custody Workflow</h2><span>Tools move differently from inventory</span></div></header><div className="fa-flow"><strong>Warehouse</strong><i>→</i><strong>Issue / Check-out</strong><i>→</i><strong>Van / Technician Custody</strong><i>→</i><strong>Inspection</strong><i>→</i><strong>Return / Transfer / Repair</strong></div></article><article className="panel"><header className="panel-head"><div><h2>Control Rules</h2><span>Asset accountability</span></div></header><div className="fa-rules"><div><strong>QR identity</strong><span>Each durable tool can be scanned and opened directly.</span></div><div><strong>Condition history</strong><span>Damage, loss and repair are events, not overwritten status only.</span></div><div><strong>Calibration</strong><span>Measurement tools can be blocked or warned when calibration expires.</span></div></div></article></section>
  </div>;
}
