import { estimates } from '@/lib/revenue-cycle';

export default function EstimatesPage() {
  return <div className="rc-stack">
    <section className="page-head"><div><div className="eyebrow">Sales · Controlled Pricing</div><h1>Estimates & Proposals</h1><p>Versioned scope, pricing and margin with controlled approvals and direct operational handoff when the customer accepts.</p></div><div className="page-actions"><button className="btn" type="button">Pricebook</button><button className="btn primary" type="button">+ Estimate</button></div></section>
    <section className="rc-metrics"><article><span>Open Value</span><strong>Afl. 135.8K</strong><small>Draft + sent + review</small></article><article><span>Accepted This Month</span><strong>Afl. 43.2K</strong><small className="rc-good">Feeds scheduling demand</small></article><article><span>Average Margin</span><strong>39%</strong><small>Across active estimates</small></article><article><span>Internal Review</span><strong>1</strong><small className="rc-warn">Pricing approval needed</small></article></section>
    <section className="panel rc-table-panel"><header className="panel-head"><div><h2>Proposal Register</h2><span>One customer scope can have controlled versions without duplicate records</span></div><span>Latest versions</span></header><div className="rc-table rc-estimate-table"><div className="rc-row rc-head"><span>Estimate</span><span>Customer / Scope</span><span>Total</span><span>Margin</span><span>Status</span><span>Next</span></div>{estimates.map(item=><div className="rc-row" key={item.number}><div><strong>{item.number}</strong><small>{item.version} · {item.age}</small></div><div><strong>{item.customer}</strong><small>{item.scope}</small></div><strong>{item.total}</strong><span>{item.margin}</span><b>{item.status}</b><span>{item.next}</span></div>)}</div></section>
    <section className="rc-two-col"><article className="panel"><header className="panel-head"><div><h2>Acceptance Handoff</h2><span>No duplicate entry after a sale</span></div></header><div className="rc-flow"><strong>Accepted Proposal</strong><i>→</i><strong>Deposit / Terms</strong><i>→</i><strong>Inventory Demand</strong><i>→</i><strong>Scheduling</strong><i>→</i><strong>Work Order</strong></div></article><article className="panel"><header className="panel-head"><div><h2>Pricing Guardrails</h2><span>Commercial control</span></div></header><div className="rc-rule-list"><div><strong>Approved pricebook</strong><span>Standard items and labor use governed prices.</span></div><div><strong>Margin visibility</strong><span>Cost and expected margin are visible before approval.</span></div><div><strong>Discount exception</strong><span>Out-of-policy discounts require elevated approval.</span></div></div></article></section>
  </div>;
}
