import { vans } from '@/lib/field-assets';

export default function VansPage() {
  return <div className="fa-stack">
    <section className="page-head"><div><div className="eyebrow">Mobile Warehouses · Fleet</div><h1>Vans & Readiness</h1><p>Each van combines crew, route, inventory, tools and job readiness. A van can be operationally blocked even when the calendar still has empty time.</p></div><div className="page-actions"><button className="btn" type="button">Replenishment</button><button className="btn primary" type="button">+ Fleet Action</button></div></section>
    <section className="fa-metrics"><article><span>Operational Vans</span><strong>4 / 4</strong><small className="fa-good">All active</small></article><article><span>Ready</span><strong>3</strong><small>1 at inventory risk</small></article><article><span>Jobs Allocated</span><strong>19</strong><small>+ linked support work</small></article><article><span>Open Replenishment</span><strong>1</strong><small className="fa-warn">Van 2 switches</small></article></section>
    <section className="fa-van-grid">{vans.map(van=><article className="panel fa-van-card" key={van.name}><div className="fa-van-head"><div><span>{van.template}</span><h2>{van.name}</h2><p>{van.crew}</p></div><b className={van.readiness==='AT RISK'?'risk':''}>{van.readiness}</b></div><div className="fa-van-context"><div><span>Sector</span><strong>{van.sector}</strong></div><div><span>Load</span><strong>{van.jobs}</strong></div></div><div className="fa-gauge"><div><span>Stock readiness</span><strong>{van.stock}%</strong></div><div className="fa-bar"><i style={{width:`${van.stock}%`}}/></div></div><div className="fa-gauge"><div><span>Fuel</span><strong>{van.fuel}%</strong></div><div className="fa-bar fuel"><i style={{width:`${van.fuel}%`}}/></div></div><div className="fa-van-alert"><span>Operational note</span><strong>{van.alerts}</strong></div></article>)}</section>
    <section className="fa-two-col"><article className="panel"><header className="panel-head"><div><h2>Readiness Gate</h2><span>Before the van leaves</span></div></header><div className="fa-rules"><div><strong>Crew & skill</strong><span>Correct team is present and qualified.</span></div><div><strong>Route</strong><span>Appointment fits AM/PM anchor and travel constraints.</span></div><div><strong>Inventory & tools</strong><span>Reserved materials and required tools are on the assigned van.</span></div><div><strong>Customer / commercial</strong><span>Confirmation, access and required deposit/PO conditions are satisfied.</span></div></div></article><article className="panel"><header className="panel-head"><div><h2>Van 2 Recommendation</h2><span>Predictive replenishment</span></div></header><div className="fa-callout warning"><strong>Transfer before tomorrow 16:00</strong><p>Projected 220V switch availability falls below Van 2 minimum before Wednesday bookings. Suggested action: transfer 6 switches from Main Warehouse.</p></div></article></section>
  </div>;
}
