import { technicianPerformance } from '@/lib/field-assets';

export default function TechniciansPage() {
  return <div className="fa-stack">
    <section className="page-head"><div><div className="eyebrow">Field Workforce</div><h1>Technicians</h1><p>Capability, current assignment and quality signals help dispatch choose the right team without turning technician performance into a disconnected spreadsheet.</p></div><div className="page-actions"><button className="btn" type="button">Skill Matrix</button><button className="btn primary" type="button">Training Plan</button></div></section>
    <section className="fa-metrics"><article><span>Field Utilization</span><strong>78%</strong><small className="fa-good">Near 82% target</small></article><article><span>First-Time Fix</span><strong>92.4%</strong><small className="fa-good">Preview average</small></article><article><span>Callback Rate</span><strong>2.4%</strong><small>Quality indicator</small></article><article><span>Skill Gap</span><strong>2</strong><small className="fa-warn">Commercial / VRF coverage</small></article></section>
    <section className="panel fa-table-panel"><header className="panel-head"><div><h2>Technician Capacity & Quality</h2><span>Operational performance with context — not a standalone score</span></div><span>Today</span></header><div className="fa-table fa-tech-table"><div className="fa-row fa-head"><span>Technician / Team</span><span>Current</span><span>Skills</span><span>Utilization</span><span>First-Time Fix</span><span>Callback</span></div>{technicianPerformance.map(item=><div className="fa-row" key={item.name}><div><strong>{item.name}</strong><small>{item.van} · {item.status}</small></div><div><strong>{item.sector}</strong><small>{item.jobs}</small></div><div className="fa-tags">{item.skills.map(skill=><b key={skill}>{skill}</b>)}</div><div><strong>{item.utilization}%</strong><div className="fa-bar"><i style={{width:`${item.utilization}%`}}/></div></div><strong>{item.firstTimeFix}%</strong><span>{item.callback}</span></div>)}</div></section>
    <section className="fa-two-col"><article className="panel"><header className="panel-head"><div><h2>Dispatch Use</h2><span>How technician data should influence scheduling</span></div></header><div className="fa-rules"><div><strong>Skills</strong><span>Commercial/VRF/diagnostics requirements can restrict eligible teams.</span></div><div><strong>Availability</strong><span>Shift, leave, current voice call and active job states affect assignment.</span></div><div><strong>Quality</strong><span>Callback patterns trigger coaching/quality review, not hidden punitive logic.</span></div></div></article><article className="panel"><header className="panel-head"><div><h2>Performance Principle</h2><span>Evidence before conclusions</span></div></header><div className="fa-callout"><strong>Context matters</strong><p>Utilization, first-time fix, upsells and callbacks should be viewed with job complexity, commercial mix and assigned workload. The ERP should surface evidence instead of ranking technicians from one metric.</p></div></article></section>
  </div>;
}
