import { invoices } from '@/lib/revenue-cycle';

export default function InvoicesPage() {
  return <div className="rc-stack">
    <section className="page-head"><div><div className="eyebrow">Finance · Accounts Receivable</div><h1>Invoices & Receivables</h1><p>Invoice-level and customer-level balances with partial payments, aging, payment evidence and collection workflow.</p></div><div className="page-actions"><button className="btn" type="button">Aging</button><button className="btn primary" type="button">+ Invoice</button></div></section>
    <section className="rc-metrics"><article><span>Total Receivable</span><strong>Afl. 37.6K</strong><small>Open customer balances</small></article><article><span>Overdue</span><strong>Afl. 12.1K</strong><small className="rc-warn">Requires collection action</small></article><article><span>Detected Payments</span><strong>6</strong><small>Awaiting allocation/review</small></article><article><span>Collection Rate</span><strong>83%</strong><small className="rc-good">Current month</small></article></section>
    <section className="panel rc-table-panel"><header className="panel-head"><div><h2>Invoice Register</h2><span>Payment status never hides remaining customer balance</span></div><span>Preview ledger</span></header><div className="rc-table rc-invoice-table"><div className="rc-row rc-head"><span>Invoice</span><span>Customer</span><span>Issued / Due</span><span>Total</span><span>Paid</span><span>Balance</span><span>Status</span></div>{invoices.map(item=><div className="rc-row" key={item.number}><strong>{item.number}</strong><span>{item.customer}</span><div><span>{item.issued}</span><small>Due {item.due}</small></div><strong>{item.total}</strong><span>{item.paid}</span><strong>{item.balance}</strong><b className={item.status==='Open'?'rc-danger':item.status==='Partial'?'rc-warning':''}>{item.status}</b></div>)}</div></section>
    <section className="rc-two-col"><article className="panel"><header className="panel-head"><div><h2>Customer Balance Example</h2><span>Aggregate payment control</span></div></header><div className="rc-balance-example"><div><span>Open invoices</span><strong>Afl. 14,000</strong></div><div><span>Detected transfer</span><strong>Afl. 13,000</strong></div><div className="remaining"><span>Remaining balance</span><strong>Afl. 1,000</strong></div><p>Suggested allocation: Afl. 5,000 + Afl. 8,000. The remaining Afl. 1,000 stays visible until paid or explicitly resolved.</p></div></article><article className="panel"><header className="panel-head"><div><h2>Allocation Policy</h2><span>Deterministic before ambiguous</span></div></header><div className="rc-rule-list"><div><strong>1 · Explicit reference</strong><span>Use customer/invoice reference when present.</span></div><div><strong>2 · Exact combination</strong><span>Match amounts across compatible open invoices.</span></div><div><strong>3 · Suggest oldest</strong><span>Only as a recommendation when evidence is weaker.</span></div><div><strong>4 · Human review</strong><span>Ambiguous payments remain unallocated.</span></div></div></article></section>
  </div>;
}
