from pathlib import Path

path = Path('ops/digitalocean/deploy/server-v2.mjs')
text = path.read_text(encoding='utf-8')

old_resolver = """async function resolveIdentity(chat, detail) {\n  if (String(chat).endsWith('@s.whatsapp.net')) {\n    return { ResolvedPhone: validPhone(String(chat).split('@')[0]), CanonicalJid: chat, WhatsAppLid: null };\n  }\n  if (!String(chat).endsWith('@lid')) return {};\n  const cached = identityCache.get(chat);\n  if (cached && Date.now() - cached.at < IDENTITY_CACHE_MS) return cached.value;\n\n  const strings = collectStrings(detail);\n  let canonical = strings.find((entry) => entry.value.endsWith('@s.whatsapp.net') && validPhone(entry.value.split('@')[0]))?.value || '';\n  if (!canonical) {\n    try {\n      const chats = await runWacliJson(['chats', 'list', '--limit', '2000'], { readOnly: true, timeout: 15000 });\n      const rows = Array.isArray(chats) ? chats : Array.isArray(chats?.chats) ? chats.chats : Array.isArray(chats?.items) ? chats.items : [];\n      const match = rows.find((row) => JSON.stringify(row).includes(chat));\n      if (match) canonical = collectStrings(match).find((entry) => entry.value.endsWith('@s.whatsapp.net') && validPhone(entry.value.split('@')[0]))?.value || '';\n    } catch {\n      // Keep the LID unresolved rather than fabricating a phone number.\n    }\n  }\n  const value = {\n    ResolvedPhone: canonical ? validPhone(canonical.split('@')[0]) : null,\n    CanonicalJid: canonical || null,\n    WhatsAppLid: chat,\n  };\n  identityCache.set(chat, { at: Date.now(), value });\n  return value;\n}\n"""
new_resolver = """async function resolveIdentity(chat, detail) {\n  const sourceChat = String(chat || '').trim();\n  if (sourceChat.endsWith('@s.whatsapp.net')) {\n    return { ResolvedPhone: validPhone(sourceChat.split('@')[0]), CanonicalJid: sourceChat, WhatsAppLid: null };\n  }\n  if (!sourceChat.endsWith('@lid')) return {};\n  const cached = identityCache.get(sourceChat);\n  if (cached && Date.now() - cached.at < IDENTITY_CACHE_MS) return cached.value;\n\n  const strings = collectStrings(detail);\n  let canonical = strings.find((entry) => entry.value.endsWith('@s.whatsapp.net') && validPhone(entry.value.split('@')[0]))?.value || '';\n  if (!canonical) {\n    try {\n      const shown = await runWacliJson(['chats', 'show', '--jid', sourceChat], { readOnly: true, timeout: 15000 });\n      canonical = collectStrings(shown).find((entry) => entry.value.endsWith('@s.whatsapp.net') && validPhone(entry.value.split('@')[0]))?.value || '';\n    } catch {\n      // Fall through to the bounded chat-list compatibility lookup.\n    }\n  }\n  if (!canonical) {\n    try {\n      const chats = await runWacliJson(['chats', 'list', '--limit', '2000'], { readOnly: true, timeout: 15000 });\n      const rows = Array.isArray(chats) ? chats : Array.isArray(chats?.chats) ? chats.chats : Array.isArray(chats?.items) ? chats.items : [];\n      const match = rows.find((row) => JSON.stringify(row).includes(sourceChat));\n      if (match) canonical = collectStrings(match).find((entry) => entry.value.endsWith('@s.whatsapp.net') && validPhone(entry.value.split('@')[0]))?.value || '';\n    } catch {\n      // Keep the LID unresolved rather than fabricating a phone number.\n    }\n  }\n  const value = {\n    ResolvedPhone: canonical ? validPhone(canonical.split('@')[0]) : null,\n    CanonicalJid: canonical || null,\n    WhatsAppLid: sourceChat,\n  };\n  if (canonical) identityCache.set(sourceChat, { at: Date.now(), value });\n  return value;\n}\n\nasync function storageChatForPayload(payload) {\n  const sourceChat = String(payload?.Chat || '').trim();\n  if (!sourceChat.endsWith('@lid')) return sourceChat;\n  const provided = String(payload?.CanonicalJid || '').trim();\n  if (provided.endsWith('@s.whatsapp.net') && validPhone(provided.split('@')[0])) return provided;\n  const resolved = await resolveIdentity(sourceChat, null);\n  const canonical = String(resolved?.CanonicalJid || '').trim();\n  if (canonical.endsWith('@s.whatsapp.net') && validPhone(canonical.split('@')[0])) return canonical;\n  throw new Error('Unable to resolve WhatsApp LID to its canonical store JID.');\n}\n"""
if text.count(old_resolver) != 1:
    raise SystemExit('unexpected resolveIdentity structure')
text = text.replace(old_resolver, new_resolver, 1)

old_enrich = """  let detail = null;\n  try {\n    detail = await runWacliJson(['messages', 'show', '--chat', chat, '--id', id], { readOnly: true, timeout: 15000 });\n  } catch {\n    // Text delivery must never depend on optional enrichment.\n  }\n\n  const identity = await resolveIdentity(chat, detail).catch(() => ({}));\n  const enriched = { ...payload, ...identity };\n  const kind = detail ? mediaKindFromDetail(detail) : null;\n  if (kind) enriched.Media = extractMediaMeta(detail, kind);\n\n  const profilePicture = await resolveProfilePicture(chat).catch(() => null);\n"""
new_enrich = """  let identity = await resolveIdentity(chat, null).catch(() => ({}));\n  let storageChat = String(identity?.CanonicalJid || chat).trim();\n  let detail = null;\n  try {\n    detail = await runWacliJson(['messages', 'show', '--chat', storageChat, '--id', id], { readOnly: true, timeout: 15000 });\n  } catch {\n    // Text delivery must never depend on optional enrichment.\n  }\n\n  if (!identity?.CanonicalJid && detail) identity = await resolveIdentity(chat, detail).catch(() => identity);\n  if (identity?.CanonicalJid) storageChat = String(identity.CanonicalJid);\n  const enriched = { ...payload, ...identity };\n  const kind = detail ? mediaKindFromDetail(detail) : null;\n  if (kind) enriched.Media = extractMediaMeta(detail, kind);\n\n  const profilePicture = await resolveProfilePicture(storageChat).catch(() => null);\n"""
if text.count(old_enrich) != 1:
    raise SystemExit('unexpected enrichIncomingPayload structure')
text = text.replace(old_enrich, new_enrich, 1)

old_upload = """  const chat = String(payload.Chat || '').trim();\n  const messageId = String(payload.ID || '').trim();\n  if (!chat || !messageId) throw new Error('Inbound media requires Chat and ID before forwarding.');\n\n  try {\n    const bytes = await downloadInboundMedia(chat, messageId);\n"""
new_upload = """  const chat = String(payload.Chat || '').trim();\n  const messageId = String(payload.ID || '').trim();\n  if (!chat || !messageId) throw new Error('Inbound media requires Chat and ID before forwarding.');\n\n  try {\n    const storageChat = await storageChatForPayload(payload);\n    const bytes = await downloadInboundMedia(storageChat, messageId);\n"""
if text.count(old_upload) != 1:
    raise SystemExit('unexpected uploadInboundMedia structure')
text = text.replace(old_upload, new_upload, 1)

path.write_text(text, encoding='utf-8')
print('CANONICAL_LID_MEDIA_MIGRATION_APPLIED')
