export const colors = {
  primary: '#2CA01C',
  primaryDark: '#188A16',
  primaryLight: '#EAF7E7',
  navy: '#0F172A',
  sidebar: '#F3F5F7',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  text: '#202124',
  muted: '#5F6368',
  border: '#DADCE0',
  success: '#188A16',
  successLight: '#EAF7E7',
  warning: '#B06000',
  warningLight: '#FFF4DE',
  danger: '#D93025',
  dangerLight: '#FDECEC',
  info: '#0B57D0',
  infoLight: '#EAF3FF',
  purple: '#6F42C1',
  brandBlue: '#0957C3',
};

export const roleLabels = {
  admin: 'Administrador',
  office: 'Oficina / Ventas',
  supervisor: 'Supervisor',
  technician: 'Técnico',
  accounting: 'Contabilidad',
  inventory: 'Control de inventario',
} as const;