export const colors = {
  primary: '#0957C3',
  primaryDark: '#073F8C',
  primaryLight: '#EAF3FF',
  navy: '#0B1220',
  sidebar: '#0B1220',
  background: '#F4F7FB',
  surface: '#FFFFFF',
  text: '#172033',
  muted: '#667085',
  border: '#E3E8EF',
  success: '#198754',
  successLight: '#EAF7F0',
  warning: '#B36B00',
  warningLight: '#FFF5E5',
  danger: '#D92D20',
  dangerLight: '#FDECEC',
  info: '#0957C3',
  infoLight: '#EAF3FF',
  purple: '#6F42C1',
  brandBlue: '#0957C3',
};

export const roleLabels = {
  admin: 'Director',
  office: 'Operaciones',
  supervisor: 'Supervisor',
  technician: 'Técnico',
  accounting: 'Contabilidad',
  inventory: 'Control de inventario',
} as const;