export const colors = {
  primary: '#2CA01C',
  primaryDark: '#108000',
  primaryLight: '#EAF7E7',
  navy: '#111827',
  sidebar: '#111827',
  background: '#F6F7F9',
  surface: '#FFFFFF',
  text: '#1F2937',
  muted: '#6B7280',
  border: '#D7DCE2',
  success: '#2CA01C',
  successLight: '#EAF7E7',
  warning: '#B7791F',
  warningLight: '#FFF4DE',
  danger: '#D93025',
  dangerLight: '#FDECEC',
  info: '#0B57D0',
  infoLight: '#EAF3FF',
  purple: '#6F42C1',
  brandBlue: '#0957C3',
};

export const roleLabels = {
  admin: 'Administrador',
  office: 'Oficina / Ventas',
  supervisor: 'Supervisor',
  technician: 'Técnico',
  accounting: 'Contabilidad',
  inventory: 'Control de inventario',
} as const;
