'use client';
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { createRegistryWriter, minutesLabel, type RegistryRequest, type IntentJournal } from '@/lib/projects/registry-client-core';
import type { CentralProject, ProjectList, ProjectActivity, MutationResult, ProjectPhasePlan } from '@/lib/projects/registry-types';
import { MetadataDialog, PhaseDialog, PlanDialog } from './project-plan-dialog';
import { ProjectImportPanel } from './project-import-panel';
import { ProjectMaterialsPanel } from './project-materials-panel';
import { ProjectEstimateDialog } from './project-estimate-dialog';
import { materialBudgetLabel } from '@/lib/projects/material-budget';
import { ProjectFieldExecution } from './project-field-execution';
import { PhaseCompletionDialog } from './phase-completion-dialog';
import { HistoryReconciliationDialog } from './history-reconciliation-dialog';
import { PhaseProgressDialog } from './phase-progress-dialog';
import { ProjectLifecycleDialog } from './project-lifecycle-dialog';
import { PhaseTemplateDialog } from './phase-template-dialog';
import s from './projects-central.module.css';

type PageState<T>={data:T|null;loading:boolean;error:string};
type Props={request:RegistryRequest;journal?:IntentJournal;canManage:boolean;isOwner:boolean;importEnabled:boolean};
const message=(error:unknown)=>error instanceof Error?error.message:'The request could not be verified.';
export function ProjectsCentralWorkspace({request,journal,canManage,isOwner,importEnabled}:Props) {
  const writer=useMemo(()=>createRegistryWriter(request,undefined,journal),[request,journal]);
  const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  const [refresh,setRefresh]=useState(0);const [cursor,setCursor]=useState<string|undefined>();const [cursors,setCursors]=useState<Array<string|undefined>>([]);
  const [list,setList]=useState<PageState<ProjectList>>({data:null,loading:true,error:''});const [filter,setFilter]=useState('');
  const [selected,setSelected]=useState('');const [detail,setDetail]=useState<PageState<{project:CentralProject;activity:ProjectActivity}>>({data:null,loading:false,error:''});
  const [activityCursor,setActivityCursor]=useState<string|undefined>();const [activityCursors,setActivityCursors]=useState<Array<string|undefined>>([]);
  const [tab,setTab]=useState('Overview');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
  const [modal,setModal]=useState<'create'|'metadata'|'estimate'|'phase'|'associate'|'completion'|'progress'|'lifecycle'|'templates'|'history'|null>(null);const [phase,setPhase]=useState<ProjectPhasePlan|undefined>();
  const locked=busy||writer.hasPending();
  useEffect(()=>{const controller=new AbortController();let current=true;setList(previous=>({...previous,loading:true,error:''}));void request<ProjectList>({action:'list_plans',data:{limit:20,...(cursor?{afterId:cursor}:{})}},controller.signal).then(data=>{
    if(data.source!=='project_registry_v1'||!Array.isArray(data.projects)||data.projects.some(project=>project.schemaVersion!==1||!project.id||!project.budget))throw Error('The server returned an unsupported project list.');
    if(current)setList({data,loading:false,error:''});
  }).catch(cause=>{if(current)setList(previous=>({...previous,loading:false,error:message(cause)}));});return()=>{current=false;controller.abort();};},[request,cursor,refresh]);
  useEffect(()=>{if(!selected){setDetail({data:null,loading:false,error:''});return;}const controller=new AbortController();let current=true;setDetail(previous=>({data:previous.data?.project.id===selected?previous.data:null,loading:true,error:''}));void Promise.all([
    request<{project:CentralProject}>({action:'get_plan',data:{projectId:selected}},controller.signal),
    request<ProjectActivity>({action:'get_activity',data:{projectId:selected,...(activityCursor?{afterId:activityCursor}:{})}},controller.signal),
  ]).then(([plan,activity])=>{if(plan.project.id!==selected||activity.projectId!==selected||plan.project.version!==activity.projectVersion)throw Error('Project changed during loading. Refresh to read a consistent version.');if(current)setDetail({data:{project:plan.project,activity},loading:false,error:''});}).catch(cause=>{if(current)setDetail(previous=>({...previous,loading:false,error:message(cause)}));});return()=>{current=false;controller.abort();};},[request,selected,activityCursor,refresh]);
  useEffect(()=>{const prevent=(event:BeforeUnloadEvent)=>{if(writer.hasPending()){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[writer]);
  const open=(id:string)=>{setSelected(id);setActivityCursor(undefined);setActivityCursors([]);setTab('Overview');};
  const finish=(result:MutationResult)=>{if(!alive.current)return;setModal(null);setNotice(`Saved in the shared registry · version ${result.version}${result.replayed?' · original request recovered':''}.`);setError('');open(result.projectId);setRefresh(value=>value+1);};
  const writeAllowed = canManage && list.data?.writeMode !== 'paused';
  const save=async(action:string,data:Record<string,unknown>)=>{if(!writeAllowed||locked)throw Error('You cannot start another write now.');setBusy(true);setError('');try{const result=await writer.start<MutationResult>(action,data);finish(result);}catch(cause){if(alive.current)setError(message(cause));throw cause;}finally{if(alive.current)setBusy(false);}};
  const retry=async()=>{if(!canManage||busy)return;setBusy(true);setError('');try{finish(await writer.retry<MutationResult>());}catch(cause){if(alive.current)setError(message(cause));}finally{if(alive.current)setBusy(false);}};
  const project=detail.data?.project;const activity=detail.data?.activity;
  const filterRows=(list.data?.projects??[]).filter(row=>`${row.name} ${row.projectNumber}`.toLowerCase().includes(filter.toLowerCase()));
  const pending=writer.pendingSummary();
  const tabs=isOwner?['Overview','Plan & phases','Scheduling activity','Field execution','Materials','Import & recovery']:['Overview','Plan & phases','Scheduling activity','Field execution','Materials'];
  return <main className={s.root}>
    <header className={s.header}><div><span className={s.eyebrow}>Commercial & project operations</span><h1>Projects</h1><p>Shared planning with traceable Scheduling and Field evidence.</p></div><div className={s.actions}><button className={s.button} type="button" onClick={()=>setRefresh(value=>value+1)} disabled={busy}>Refresh</button><button className={s.primary} type="button" disabled={!writeAllowed||locked} onClick={()=>setModal('create')}>＋ Create Project</button></div></header>
    <div className={s.notice}><strong>Central Projects integration preview.</strong> This workspace uses the registry service, not the browser project list. The existing live Projects and Scheduling pages remain unchanged. Automatic booking handoff, measured-time reconciliation and cost integration are not activated here.</div>
    {list.data?.writeMode==='paused'&&<p className={s.warning} role="status">Project changes are paused. You are viewing current shared records, not an older browser copy. Previously committed requests can still be recovered.</p>}
    {notice&&<p className={s.notice} role="status">{notice}</p>}{error&&<p className={s.error} role="alert">{error}</p>}
    {pending&&!busy&&<div className={s.warning} role="alert"><strong>An earlier operation needs confirmation.</strong><p>{pending.action.replaceAll('_',' ')} · {pending.requestId}. New writes are paused. The exact request is retained for this signed-in user in session storage; it is not a saved Project. Do not create a replacement.</p><button type="button" className={s.button} disabled={!canManage} onClick={()=>void retry()}>Retry the exact request</button></div>}
    {!selected&&<section className={s.card}><div className={s.toolbar}><h2>Shared project records</h2><label className={s.form}>Filter this page<input aria-label="Filter projects on this page" value={filter} onChange={event=>setFilter(event.target.value)} /></label></div>
      {list.loading&&<p role="status">Loading shared records…</p>}{list.error&&<p className={s.error} role="alert">{list.error}{list.data?' Previously loaded records below may be stale.':''}</p>}
      {!list.loading&&!list.error&&filterRows.length===0&&<p className={s.empty}>{list.data?.projects.length?'No match on this page.':'No central projects on this page. Browser-only projects have not been imported automatically.'}</p>}
      {filterRows.length>0&&<div className={s.tableScroll}><table className={s.table}><thead><tr><th>Project</th><th>Planning estimate</th><th>Phases</th><th>Record status</th><th>Action</th></tr></thead><tbody>{filterRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.projectNumber}</small></td><td>{minutesLabel(row.budget.currentMinutes)}<small>Original: {minutesLabel(row.budget.originalMinutes)}</small></td><td>{row.phases.length}</td><td><span className={s.badge}>{row.migration?.status==='pending_reconciliation'?'Reconciliation pending':row.planningStatus}</span><small>Version {row.version} · not an execution certificate</small></td><td><button className={s.button} type="button" onClick={()=>open(row.id)} disabled={busy}>Open project</button></td></tr>)}</tbody></table></div>}
      <div className={s.pager}><button className={s.button} type="button" disabled={!cursors.length||list.loading} onClick={()=>{setCursor(cursors.at(-1));setCursors(current=>current.slice(0,-1));setFilter('');}}>Previous page</button><span className={s.muted}>Up to 20 records per page · no portfolio-wide totals inferred</span><button className={s.button} type="button" disabled={!list.data?.nextCursor||list.loading||Boolean(list.error)} onClick={()=>{setCursors(current=>[...current,cursor]);setCursor(list.data!.nextCursor!);setFilter('');}}>Next page</button></div>
      {isOwner&&<p><button type="button" className={s.button} onClick={()=>setTab('Import & recovery')}>Import & recovery</button></p>}
    </section>}
    {selected&&<><div className={s.toolbar}><button className={s.button} type="button" onClick={()=>{setSelected('');setTab('Overview');}} disabled={busy}>← All projects</button>{project&&<span className={s.muted}>{project.projectNumber} · Version {project.version}</span>}</div>{detail.loading&&<p role="status">Loading project and operational evidence…</p>}{detail.error&&<p className={s.error} role="alert">{detail.error}{project?' Previously loaded data is shown as stale; editing is paused.':''}</p>}
      {project&&activity&&<><section className={s.card}><div className={s.sectionTitle}><div><h2>{project.name}</h2><span className={s.muted}>{project.type} · {project.planningStatus}</span></div><button className={s.button} type="button" disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)} onClick={()=>setModal('metadata')}>Edit plan</button><button className={s.button} type="button" disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)} onClick={()=>setModal('lifecycle')}>Change Project status</button></div>{project.migration&&<div className={s.notice}><p>{project.migration.status==='history_reviewed'?'Imported scheduling references reviewed. Archived amounts are still not certified worked hours, costs or completed scope.':'Imported planning record: historical scheduling references still require review.'}</p>{isOwner&&<button type="button" className={s.button} disabled={locked||detail.loading||Boolean(detail.error)} onClick={()=>setModal('history')}>Review imported history</button>}</div>}</section>
      <div className={s.tabs} role="tablist" aria-label="Project sections">{tabs.map(name=><button role="tab" key={name} aria-selected={tab===name} className={s.tab} type="button" onClick={()=>setTab(name)}>{name}</button>)}</div>
      {tab==='Overview'&&<><section className={s.grid}><Metric label="Original estimate" value={minutesLabel(project.budget.originalMinutes)}/><Metric label="Current estimate" value={minutesLabel(project.budget.currentMinutes)}/><Metric label="Planned Van time · this page" value={minutesLabel(activity.pageTotals.plannedVanMinutes)}/><Metric label="Verified actual labor" value={minutesLabel(activity.actualLabor.personMinutes)}/><Metric label="Physical progress" value={activity.physicalProgress.percent===null?'Not reconciled':`${activity.physicalProgress.percent}%`}/></section>
      {activity.projectForecast?<p className={activity.projectForecast.overBudgetMinutes>0?s.warning:s.notice}>Recorded allocation against estimate: {minutesLabel(activity.projectForecast.plannedMinutes)} / {minutesLabel(activity.projectForecast.budgetMinutes)}. Forecast over budget: +{minutesLabel(activity.projectForecast.overBudgetMinutes)}. <strong>Budget never blocks an otherwise valid booking.</strong></p>:<p className={s.notice}>No full-project allocation total is certified from this page. All linked appointments and reconciliation checks must be included before a project-wide comparison is displayed.</p>}
      <section className={s.card}><h2>Scope and identity</h2><dl className={s.detailList}><dt>Customer ID</dt><dd>{project.customerId}</dd><dt>Property ID</dt><dd>{project.propertyId}</dd><dt>Start / estimated completion</dt><dd>{project.startsOn} → {project.estimatedCompletionOn}</dd></dl><p className={s.prewrap}>{project.description||'No description recorded.'}</p><h3>Technician instructions</h3><p className={s.prewrap}>{project.technicianInstructions||'No instructions recorded.'}</p></section></>}
      {tab==='Plan & phases'&&<section className={s.card}><div className={s.sectionTitle}><h2>Custom project phases</h2><button type="button" className={s.button} disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)} onClick={()=>{setPhase(undefined);setModal('phase');}}>Add phase</button><button type="button" className={s.button} disabled={locked||detail.loading||Boolean(detail.error)} onClick={()=>setModal('templates')}>Company templates</button></div>{!project.phases.length&&<p className={s.empty}>General Project Work — no phases defined. Existing linked general work remains visible.</p>}{project.phases.map(item=><article className={s.card} key={item.id}><div className={s.sectionTitle}><h3>{item.name}</h3><button className={s.button} type="button" disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)} onClick={()=>{setPhase(item);setModal('phase');}}>Edit phase</button><button className={s.button} type="button" disabled={locked||detail.loading||Boolean(detail.error)} onClick={()=>{setPhase(item);setModal('completion');}}>Review completion</button><button className={s.button} type="button" disabled={locked||detail.loading||Boolean(detail.error)} onClick={()=>{setPhase(item);setModal('progress');}}>Review partial progress</button></div><p>{minutesLabel(item.plannedVanMinutes)} planned · Completion method: {item.progressMethod}</p><p className={s.prewrap}>{item.scopeOfWork}</p><p><strong>Completion criteria:</strong> {item.completionCriteria}</p><p className={s.muted}>Prerequisites: {item.dependencies.map(id=>project.phases.find(row=>row.id===id)?.name??id).join(', ')||'None'}</p></article>)}</section>}
      {tab==='Overview'&&<section className={s.card}>
        <div className={s.sectionTitle}><h2>Planning budgets</h2>
          <button type="button" className={s.button} disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)||['Completed','Cancelled'].includes(project.planningStatus)} onClick={()=>setModal('estimate')}>Revise estimate</button>
        </div>
        <p>Van estimate revision {project.budget.revision}. The original estimate remains {minutesLabel(project.budget.originalMinutes)}.</p>
        {project.type!=='Service Project'&&<p>Material budget: {project.details?.materialBudget
          ? materialBudgetLabel(project.details.materialBudget)
          : 'Not estimated'}. Planning only; actual material cost requires historical source evidence.</p>}
      </section>}
      {tab==='Materials'&&<ProjectMaterialsPanel key={`${project.id}:${project.version}:${activityCursor||'first'}`} project={project} activity={activity} request={request}/>}
      {tab==='Field execution'&&<ProjectFieldExecution key={project.id} request={request} projectId={project.id} projectVersion={project.version} refreshToken={refresh}/>}
      {tab==='Scheduling activity'&&<section className={s.card}><div className={s.sectionTitle}><h2>Canonical activity · current page</h2><button type="button" className={s.button} disabled={!writeAllowed||locked||detail.loading||Boolean(detail.error)} onClick={()=>setModal('associate')}>Associate existing appointment</button></div><p className={s.muted}>This is a read of existing Work Orders and Field visits. Associating history does not reserve new capacity or change a technician report.</p>{activity.issues.length>0&&<div className={s.warning}>{activity.issues.map((issue,index)=><p key={`${issue.code}-${index}`}>{issue.code.replaceAll('_',' ')} {issue.workOrderId??issue.appointmentId??''}</p>)}</div>}
      {!activity.rows.length&&<p className={s.empty}>No linked Work Orders on this page. This does not prove that no project work was performed.</p>}
      {activity.rows.map(row=><article className={s.card} key={row.workOrderId}><div className={s.sectionTitle}><strong>{row.date??'Date not recorded'} · {row.start??''} · {row.vanId??'Van unresolved'}</strong><span className={s.badge}>{row.cancelled?'Cancelled — excluded from allocation':row.status}</span></div><p>{row.workOrderId} · {row.phaseId?project.phases.find(item=>item.id===row.phaseId)?.name??row.phaseId:'General Project Work'}</p><p>{row.scheduledSlots??'Unknown'} slots · {minutesLabel(row.plannedVanMinutes)} planned · Office review: {row.review?.status??'No review evidence'}</p>{row.visits.map(visit=><p key={visit.id} className={s.muted}>Visit {visit.id} · {visit.status} · Start {visit.startedAt??'not recorded'} · End {visit.completedAt??'not recorded'}</p>)}<small className={s.muted}>Visit timestamps are not pause-aware worked hours.</small></article>)}
      <div className={s.pager}><button className={s.button} type="button" disabled={!activityCursors.length||detail.loading} onClick={()=>{setActivityCursor(activityCursors.at(-1));setActivityCursors(current=>current.slice(0,-1));}}>Previous activity</button><button className={s.button} type="button" disabled={!activity.nextCursor||detail.loading} onClick={()=>{setActivityCursors(current=>[...current,activityCursor]);setActivityCursor(activity.nextCursor!);}}>Next activity</button></div></section>}
      </>}
    </>}
    {tab==='Import & recovery'&&isOwner&&<ProjectImportPanel request={request} enabled={importEnabled} locked={locked} onApply={save}/>}
    {modal==='history'&&project&&isOwner&&<HistoryReconciliationDialog key={`${project.id}:${project.version}`} project={project} request={request} busy={locked} canManage={writeAllowed} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='create'&&<MetadataDialog busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='metadata'&&project&&<MetadataDialog key={`${project.id}:${project.version}`} project={project} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='estimate'&&project&&<ProjectEstimateDialog key={`${project.id}:${project.version}`} project={project} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='phase'&&project&&<PhaseDialog project={project} phase={phase} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='completion'&&project&&phase&&<PhaseCompletionDialog project={project} phase={phase} request={request} canManage={writeAllowed} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='progress'&&project&&phase&&<PhaseProgressDialog key={`${project.id}:${project.version}:${phase.id}`} project={project} phase={phase} request={request} canManage={writeAllowed} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='lifecycle'&&project&&<ProjectLifecycleDialog key={`${project.id}:${project.version}`} project={project} request={request} canManage={writeAllowed} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='templates'&&project&&<PhaseTemplateDialog key={`${project.id}:${project.version}`} project={project} request={request} canManage={writeAllowed} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
    {modal==='associate'&&project&&<AssociateDialog project={project} busy={locked} onClose={()=>setModal(null)} onSave={save}/>}
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={`${s.card} ${s.metric}`}><span>{label}</span><strong>{value}</strong></div>;}
function AssociateDialog({project,busy,onClose,onSave}:{project:CentralProject;busy:boolean;onClose:()=>void;onSave:(action:string,data:Record<string,unknown>)=>Promise<void>}) {
  const [error,setError]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');const form=new FormData(event.currentTarget);try{await onSave('attach_existing_appointment',{projectId:project.id,expectedVersion:project.version,appointmentId:String(form.get('appointment')??'').trim(),phaseId:String(form.get('phase')??'')||null,reason:String(form.get('reason')??'').trim(),confirmedAssociation:form.get('confirmed')==='on'});}catch(cause){setError(message(cause));}};
  return <PlanDialog title="Associate existing appointment" busy={busy} onClose={onClose}><form className={s.form} onSubmit={event=>void submit(event)}><p className={s.notice}>Reconciliation only. The server checks the appointment and all related Work Orders against this customer and property. This does not create or reschedule a booking.</p><label>Canonical appointment ID<input name="appointment" disabled={busy} required maxLength={180}/></label><label>Phase<select name="phase" disabled={busy}><option value="">General Project Work</option>{project.phases.map(phase=><option key={phase.id} value={phase.id}>{phase.name}</option>)}</select></label><label>Reason for this association<textarea name="reason" disabled={busy} required maxLength={1000}/></label><label className={s.check}><input name="confirmed" type="checkbox" required disabled={busy}/>I reviewed this appointment and confirm that it belongs to this project and phase.</label>{error&&<p className={s.error} role="alert">{error}</p>}<button className={s.primary} type="submit" disabled={busy}>Save reviewed association</button></form></PlanDialog>;
}
